import React from "react";
import { ShieldAlert, Sparkles, Gauge } from "lucide-react";
import { AppLayout } from "@/components/layout/AppLayout";
import { SectionHeader } from "@/components/shared/SectionHeader";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Badge, statusTone } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { RiskDonut } from "@/components/charts/RiskDonut";
import { useAppStore } from "@/hooks/useAppStore";
import { initialAIFindings } from "@/data/mockData";

export default function AISafetyAnalysis() {
  const { safetyScore, riskLevel, anomalyScore, timeline, failures } = useAppStore();
  const activeFailures = failures.filter((f) => f.active);

  const distribution = [
    { name: "Low", value: riskLevel === "low" ? 60 : 25, color: "#37D399" },
    { name: "Moderate", value: riskLevel === "moderate" ? 55 : 30, color: "#F5A623" },
    { name: "High", value: riskLevel === "high" ? 50 : 15, color: "#F0555A" },
    { name: "Critical", value: riskLevel === "critical" ? 45 : 8, color: "#9B0F14" },
  ];

  const confidence = Math.max(72, 96 - activeFailures.length * 3);

  return (
    <AppLayout title="AI Safety Analysis" subtitle="Model-derived findings synthesized from live simulation and failure injection data">
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-4">
        <Card className="p-4 lg:col-span-1">
          <p className="text-[11px] font-medium uppercase tracking-wide text-ink-faint">Safety Score</p>
          <p className="mt-1 font-mono text-3xl font-semibold tabular text-signal">{safetyScore}</p>
          <Progress value={safetyScore} tone={safetyScore > 84 ? "safe" : safetyScore > 64 ? "amber" : "critical"} className="mt-3" />
          <div className="mt-4 flex items-center justify-between">
            <span className="text-xs text-ink-muted">Risk level</span>
            <Badge tone={statusTone(riskLevel)}>{riskLevel}</Badge>
          </div>
          <div className="mt-2 flex items-center justify-between">
            <span className="text-xs text-ink-muted">Anomaly score</span>
            <span className="font-mono text-xs font-semibold text-amber">{anomalyScore}</span>
          </div>
        </Card>

        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>Risk Distribution</CardTitle>
          </CardHeader>
          <CardContent className="flex items-center gap-4 pt-0">
            <RiskDonut data={distribution} />
            <div className="flex flex-col gap-2">
              {distribution.map((d) => (
                <div key={d.name} className="flex items-center gap-2 text-xs">
                  <span className="h-2 w-2 rounded-full" style={{ backgroundColor: d.color }} />
                  <span className="text-ink-muted">{d.name}</span>
                  <span className="font-mono text-ink">{d.value}%</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card className="p-4">
          <div className="flex items-center gap-2">
            <Gauge className="h-4 w-4 text-violet" />
            <p className="text-[11px] font-medium uppercase tracking-wide text-ink-faint">Model Confidence</p>
          </div>
          <p className="mt-1 font-mono text-3xl font-semibold tabular text-violet">{confidence}%</p>
          <p className="mt-2 text-xs text-ink-muted">Based on {timeline.length} observed simulation events and {activeFailures.length} active fault conditions.</p>
        </Card>
      </div>

      <div className="mt-4">
        <SectionHeader title="AI Findings" description="Recommendations generated by correlating anomaly timelines across recent simulation runs" />
        <div className="flex flex-col gap-3">
          {initialAIFindings.map((f) => (
            <Card key={f.id} className="p-4">
              <div className="flex items-start justify-between gap-3">
                <div className="flex items-start gap-3">
                  <div className={`mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-md border ${f.severity === "critical" ? "border-critical/30 bg-critical/10" : f.severity === "warning" ? "border-amber/30 bg-amber/10" : "border-safe/30 bg-safe/10"}`}>
                    <ShieldAlert className={`h-4 w-4 ${f.severity === "critical" ? "text-critical" : f.severity === "warning" ? "text-amber" : "text-safe"}`} />
                  </div>
                  <div>
                    <p className="text-sm font-medium text-ink">{f.title}</p>
                    <p className="mt-1 text-xs text-ink-muted">{f.description}</p>
                    <div className="mt-2 flex items-center gap-1.5 rounded-md bg-panel-raised px-2.5 py-1.5">
                      <Sparkles className="h-3 w-3 text-signal" />
                      <p className="text-[11px] text-ink"><span className="text-ink-faint">Recommendation: </span>{f.recommendation}</p>
                    </div>
                  </div>
                </div>
                <div className="flex shrink-0 flex-col items-end gap-1.5">
                  <Badge tone={statusTone(f.severity)}>{f.severity}</Badge>
                  <span className="font-mono text-[10px] text-ink-faint">{f.confidence}% confidence</span>
                </div>
              </div>
            </Card>
          ))}
        </div>
      </div>

      <div className="mt-4">
        <Card>
          <CardHeader>
            <CardTitle>Anomaly Timeline</CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <div className="flex flex-wrap gap-2">
              {timeline.slice(0, 20).map((evt) => (
                <div key={evt.id} className={`flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[11px] ${evt.severity === "critical" ? "border-critical/30 text-critical" : evt.severity === "warning" ? "border-amber/30 text-amber" : "border-hairline text-ink-muted"}`}>
                  <span className="font-mono">t+{evt.t}s</span>
                  <span className="text-ink-faint">·</span>
                  <span>{evt.label}</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </AppLayout>
  );
}
