/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiSafetyAnalysisRouteImport } from './routes/ai-safety-analysis'
import { Route as DatasetExplorerRouteImport } from './routes/dataset-explorer'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as FailureInjectionRouteImport } from './routes/failure-injection'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RiskAssessmentRouteImport } from './routes/risk-assessment'
import { Route as ScenarioGeneratorRouteImport } from './routes/scenario-generator'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TestResultsRouteImport } from './routes/test-results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSafetyAnalysisRoute = AiSafetyAnalysisRouteImport.update({
  id: '/ai-safety-analysis',
  path: '/ai-safety-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetExplorerRoute = DatasetExplorerRouteImport.update({
  id: '/dataset-explorer',
  path: '/dataset-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const FailureInjectionRoute = FailureInjectionRouteImport.update({
  id: '/failure-injection',
  path: '/failure-injection',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskAssessmentRoute = RiskAssessmentRouteImport.update({
  id: '/risk-assessment',
  path: '/risk-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioGeneratorRoute = ScenarioGeneratorRouteImport.update({
  id: '/scenario-generator',
  path: '/scenario-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TestResultsRoute = TestResultsRouteImport.update({
  id: '/test-results',
  path: '/test-results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-safety-analysis': typeof AiSafetyAnalysisRoute
  '/dataset-explorer': typeof DatasetExplorerRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/failure-injection': typeof FailureInjectionRoute
  '/reports': typeof ReportsRoute
  '/risk-assessment': typeof RiskAssessmentRoute
  '/scenario-generator': typeof ScenarioGeneratorRoute
  '/settings': typeof SettingsRoute
  '/test-results': typeof TestResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-safety-analysis': typeof AiSafetyAnalysisRoute
  '/dataset-explorer': typeof DatasetExplorerRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/failure-injection': typeof FailureInjectionRoute
  '/reports': typeof ReportsRoute
  '/risk-assessment': typeof RiskAssessmentRoute
  '/scenario-generator': typeof ScenarioGeneratorRoute
  '/settings': typeof SettingsRoute
  '/test-results': typeof TestResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-safety-analysis': typeof AiSafetyAnalysisRoute
  '/dataset-explorer': typeof DatasetExplorerRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/failure-injection': typeof FailureInjectionRoute
  '/reports': typeof ReportsRoute
  '/risk-assessment': typeof RiskAssessmentRoute
  '/scenario-generator': typeof ScenarioGeneratorRoute
  '/settings': typeof SettingsRoute
  '/test-results': typeof TestResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-safety-analysis'
    | '/dataset-explorer'
    | '/digital-twin'
    | '/failure-injection'
    | '/reports'
    | '/risk-assessment'
    | '/scenario-generator'
    | '/settings'
    | '/test-results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-safety-analysis'
    | '/dataset-explorer'
    | '/digital-twin'
    | '/failure-injection'
    | '/reports'
    | '/risk-assessment'
    | '/scenario-generator'
    | '/settings'
    | '/test-results'
  id:
    | '__root__'
    | '/'
    | '/ai-safety-analysis'
    | '/dataset-explorer'
    | '/digital-twin'
    | '/failure-injection'
    | '/reports'
    | '/risk-assessment'
    | '/scenario-generator'
    | '/settings'
    | '/test-results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiSafetyAnalysisRoute: typeof AiSafetyAnalysisRoute
  DatasetExplorerRoute: typeof DatasetExplorerRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  FailureInjectionRoute: typeof FailureInjectionRoute
  ReportsRoute: typeof ReportsRoute
  RiskAssessmentRoute: typeof RiskAssessmentRoute
  ScenarioGeneratorRoute: typeof ScenarioGeneratorRoute
  SettingsRoute: typeof SettingsRoute
  TestResultsRoute: typeof TestResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-safety-analysis': {
      id: '/ai-safety-analysis'
      path: '/ai-safety-analysis'
      fullPath: '/ai-safety-analysis'
      preLoaderRoute: typeof AiSafetyAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset-explorer': {
      id: '/dataset-explorer'
      path: '/dataset-explorer'
      fullPath: '/dataset-explorer'
      preLoaderRoute: typeof DatasetExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failure-injection': {
      id: '/failure-injection'
      path: '/failure-injection'
      fullPath: '/failure-injection'
      preLoaderRoute: typeof FailureInjectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-assessment': {
      id: '/risk-assessment'
      path: '/risk-assessment'
      fullPath: '/risk-assessment'
      preLoaderRoute: typeof RiskAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario-generator': {
      id: '/scenario-generator'
      path: '/scenario-generator'
      fullPath: '/scenario-generator'
      preLoaderRoute: typeof ScenarioGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-results': {
      id: '/test-results'
      path: '/test-results'
      fullPath: '/test-results'
      preLoaderRoute: typeof TestResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiSafetyAnalysisRoute: AiSafetyAnalysisRoute,
  DatasetExplorerRoute: DatasetExplorerRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  FailureInjectionRoute: FailureInjectionRoute,
  ReportsRoute: ReportsRoute,
  RiskAssessmentRoute: RiskAssessmentRoute,
  ScenarioGeneratorRoute: ScenarioGeneratorRoute,
  SettingsRoute: SettingsRoute,
  TestResultsRoute: TestResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
